/*
Created: 09:08:2026 - 00:16:55
Last updated: 09:08:2026 - 00:16:55
Module: engine/core/config
File: engine/core/config/sources/Constants.h

Responsibility:
- The consuming side of the generated constants: single include point through
  which all engine/game code reaches the values generated from docs/NUMBERS.md
  (Q54, Rule 14). Code includes THIS header, never the generated file directly.

Key items:
- Re-export of dfn_generated/Constants.h (emitted by tools/gen_constants into
  the build tree; lead-owned tool, contract documented below).

Dependencies:
- Uses: the generated header only.
- Used by: every module that needs a numeric constant (time, world, gameplay...).

AI Agents Notice (must follow):
- Follow docs/ARCHITECTURE.md strictly.
- Never hardcode a value that belongs in NUMBERS.md (Rule 14); if a constant is
  missing, it gets added to NUMBERS.md first, then regenerated — never inlined.
- This wrapper stays one include; do not add hand-written constants here.
*/
/*
UPD:
- 09:08:2026 - 00:16:55: Stage 1 contract — consuming-side wrapper; generation
  contract agreed with the lead (emit path, naming, types).
*/

#pragma once

// Generated by tools/gen_constants (lead-owned) from docs/NUMBERS.md into the
// build tree; the config CMake target adds the emit directory to the include
// path. The tool arrives with stage 2 — until then this include is the declared
// contract, not yet satisfiable (stage 1 has no build).
//
// Generation contract (agreed with the lead, Rule 26):
// - Path: <build>/dfn_generated/Constants.h
// - Namespace: dfn::config, everything inline constexpr.
// - Names exactly as in the NUMBERS.md tables. Types by kind of value:
//     SIM_TICK_RATE          uint32_t   (Hz)
//     SIM_DT                 double     (seconds, 1.0 / SIM_TICK_RATE)
//     WALK_SPEED, RUN_SPEED  float      (m/s)
//     CHUNK_SIZE             float      (meters)
//     HEIGHTMAP_RESOLUTION   uint32_t   (samples per side, 129)
//     HEIGHTMAP_STEP         float      (meters)
//   plus every future NUMBERS.md scalar; ranges/dimensioned pairs get _MIN/_MAX
//   or _X/_Y suffixed scalars.
// - Units follow Rule 14 (meters, seconds, radians); the generator converts
//   only representation, never units.
#include "dfn_generated/Constants.h"
