/*
Module: tests
File: tests/core/LayoutLoadTests.cpp

Responsibility:
- The migration guard for CODE_AUDIT §3.4: the shipped map asset must
  reproduce the layout the engine currently compiles in, EXACTLY, so the
  compiled copy can be deleted without a single generated byte moving. Plus
  the loader's own strictness (unknown key, missing key, bad type, bad enum)
  and a coverage control that catches a field the loader forgets to read.

Dependencies:
- Uses: doctest, dfn_world (LayoutLoad, TestbedLayout), dfn_core (Json).
- Used by: ctest (test_layout_load).

AI Agents Notice (must follow):
- Follow docs/ARCHITECTURE.md strictly.
- THE EQUIVALENCE CASE IS THE WHOLE POINT AND IT IS TEMPORARY BY DESIGN. It
  compares the asset against the compiled defaults. The day those defaults are
  deleted this case loses its reference and must be replaced by a pinned
  digest of the generated world, NOT quietly weakened to compare the asset
  against itself — which would pass forever and prove nothing.
*/

#include "engine/core/serialization/sources/Json.h"
#include "engine/world/sources/LayoutLoad.h"
#include "engine/world/sources/WorldgenForest.h"

#include <vector>
#include <doctest/doctest.h>
#include <fstream>
#include <sstream>
#include <string>

using namespace dfn;
using world::TestbedLayout;

namespace {

constexpr const char* ASSET = "games/daggerfall_n/assets/world/testbed_layout.json";

/// Field-wise digest of a layout.
///
/// NOT memcmp, and the reason is a measurement rather than taste: comparing
/// these structs byte-wise reports differences that are not differences.
/// `TestbedLayout` carries padding after `stand`, after each `SiteLayout::kind`
/// and after each `CarveCorridor::daylight_portals`, and value-initialization
/// does not guarantee those bytes agree between two objects — the compiled
/// default's `lakeshore_adit` padding reads 41 3d ee here while a freshly
/// loaded one reads 00 00 00. A byte comparison is an instrument that measures
/// the STRUCT when the claim is about the LAYOUT.
///
/// The obvious weakness of a hand-written digest is that it can forget a field.
/// That is what the static_assert below is for: adding a field to
/// TestbedLayout changes its size, the assert fires, and whoever added it is
/// told to come here. A comment asking them to would not be a mechanism.
static_assert(sizeof(world::TestbedLayout) == 1028,
              "TestbedLayout changed size: add the new field to digest() below, "
              "then update this number. This assert exists so an added field "
              "cannot silently escape the migration guard.");

struct Digest {
    std::vector<double> v;
    void operator()(float x) { v.push_back(static_cast<double>(x)); }
    void operator()(int x) { v.push_back(static_cast<double>(x)); }
    void operator()(bool x) { v.push_back(x ? 1.0 : 0.0); }
    void operator()(glm::vec2 p) { (*this)(p.x); (*this)(p.y); }
    void operator()(glm::vec3 p) { (*this)(p.x); (*this)(p.y); (*this)(p.z); }
    void operator()(glm::vec4 p) { (*this)(p.x); (*this)(p.y); (*this)(p.z); (*this)(p.w); }
    void corridor(const world::CarveCorridor& c) {
        (*this)(c.point_count);
        for (int i = 0; i < c.point_count; ++i) (*this)(c.points[i]);
        (*this)(c.half_width); (*this)(c.height); (*this)(c.daylight_portals);
    }
};

std::vector<double> digest(const world::TestbedLayout& l) {
    Digest d;
    d(l.erosion);
    d(static_cast<int>(l.stand));
    d(l.crag.center); d(l.crag.radius); d(l.crag.peak_height);
    d(l.crag.rockline); d(l.crag.treeline); d(l.crag.arete_count);
    d(l.crag.ridge_cell); d(l.crag.ridge_amp_frac); d(l.crag.ridge_amp_meters);
    for (const world::BumpStamp* b : {&l.knoll, &l.bluff}) {
        d(b->center); d(b->radius); d(b->height);
    }
    d(l.lake.center); d(l.lake.half_extent); d(l.lake.rim_rise);
    d(l.lake.rim_band_frac); d(l.lake.rim_fade_frac); d(l.lake.outlet_dir); d(l.lake.outlet_bias);
    d(l.river.source); d(l.river.source_search_radius);
    for (const world::ValleyTrough& t : l.troughs) {
        d(t.point_count);
        for (int i = 0; i < t.point_count; ++i) d(t.points[i]);
        d(t.half_width); d(t.floor_source); d(t.floor_mouth); d(t.wall_height); d(t.shoulder_frac);
    }
    for (const world::SiteLayout& st : l.sites) { d(st.position); d(static_cast<int>(st.kind)); }
    for (const world::CorridorLayout& c : l.corridors) {
        d(c.point_count);
        for (int i = 0; i < c.point_count; ++i) d(c.points[i]);
    }
    d(l.watchpoint);
    d(l.castle.center); d(l.castle.approach_corridor);
    d.corridor(l.carves.crag_tunnel);
    d.corridor(l.carves.barrow_passage);
    d.corridor(l.carves.lakeshore_adit);
    d(l.carves.barrow_chamber.center); d(l.carves.barrow_chamber.half_extent);
    d(l.carves.barrow_site_index); d(l.carves.lakeshore_site_index);
    for (const glm::vec4& r : l.forests.oak_rects) d(r);
    d(l.forests.pine_annulus_r0); d(l.forests.pine_annulus_r1);
    d(l.forests.pine_strip_count); d(l.forests.pine_strip_duty); d(l.forests.pine_strip);
    d(l.forests.forced_clearing_center); d(l.forests.forced_clearing_radius);
    return d.v;
}

std::string read_asset() {
    std::ifstream in(ASSET, std::ios::binary);
    REQUIRE_MESSAGE(in.good(), "cannot open " << ASSET << " (run ctest from the repo root)");
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

world::LayoutLoadResult load_text(const std::string& text, world::TestbedLayout& out) {
    const serialization::JsonParseResult p = serialization::json_parse(text);
    REQUIRE(p.ok);
    return world::load_layout(p.root, out);
}

} // namespace

TEST_CASE("the shipped map asset reproduces the compiled layout exactly") {
    const TestbedLayout compiled{}; // the 441 lines this migration retires
    TestbedLayout loaded{};
    const world::LayoutLoadResult r = world::load_layout_file(ASSET, loaded);
    INFO(r.error);
    REQUIRE(r.ok);

    // Named checks first, so a failure says WHAT moved rather than "digests
    // differ". These carry an anchored transform — the fields a careless
    // migration would bake into the asset as post-scale literals.
    CHECK(loaded.crag.peak_height == compiled.crag.peak_height);
    CHECK(loaded.crag.rockline == compiled.crag.rockline);
    CHECK(loaded.crag.treeline == compiled.crag.treeline);
    REQUIRE(loaded.carves.crag_tunnel.point_count == compiled.carves.crag_tunnel.point_count);
    for (int i = 0; i < compiled.carves.crag_tunnel.point_count; ++i) {
        INFO("crag tunnel waypoint " << i);
        // EXACT, not approximate. This is the assertion that caught the loader
        // reproducing spanz(225.6f) one ULP low, because clang had fused the
        // multiply-add when folding the compiled constant and the runtime
        // expression had not. A tolerance here would have hidden it, and a
        // moved waypoint moves generated bytes (Rule 13.1).
        CHECK(loaded.carves.crag_tunnel.points[i].x == compiled.carves.crag_tunnel.points[i].x);
        CHECK(loaded.carves.crag_tunnel.points[i].y == compiled.carves.crag_tunnel.points[i].y);
        CHECK(loaded.carves.crag_tunnel.points[i].z == compiled.carves.crag_tunnel.points[i].z);
    }

    // Then every field, via the digest. The named checks above cannot be
    // exhaustive by hand — that is exactly how a shadow copy drifts (Rule 39) —
    // so the binding assertion is the one no author has to remember to write.
    CHECK(digest(loaded) == digest(compiled));
}

TEST_CASE("control: the equivalence assertion actually fails on a moved map") {
    // Rule 30. An equivalence test that cannot go red would pass just as
    // happily against an asset full of zeroes, and this migration's whole
    // safety argument rests on it going red.
    const TestbedLayout compiled{};
    std::string text = read_asset();

    SUBCASE("a moved hamlet is caught") {
        const auto at = text.find("[360.0, 500.0]");
        REQUIRE(at != std::string::npos);
        text.replace(at, std::string("[360.0, 500.0]").size(), "[361.0, 500.0]");
        TestbedLayout moved{};
        REQUIRE(load_text(text, moved).ok);
        CHECK(digest(moved) != digest(compiled));
    }

    SUBCASE("a fraction written as the metres it happens to equal is caught") {
        // The exact mistake the anchored split exists to prevent: 0.65 of the
        // summit baked as 74.75 m. It parses, it loads, and it is wrong — which
        // is why the guard is a comparison and not a schema.
        const auto at = text.find("\"rockline_frac\": 0.65");
        REQUIRE(at != std::string::npos);
        text.replace(at, std::string("\"rockline_frac\": 0.65").size(), "\"rockline_frac\": 74.75");
        TestbedLayout baked{};
        REQUIRE(load_text(text, baked).ok);
        CHECK(baked.crag.rockline != compiled.crag.rockline);
    }

    SUBCASE("a one-ULP waypoint shift is caught") {
        // The failure this suite actually found. 225.60002 is the NEXT
        // representable float above 225.6 (ulp = 1.53e-05 at this magnitude);
        // my first attempt used 225.60001, which rounds to the same float and
        // made the control silently vacuous — a control that cannot fail is
        // the thing this project keeps finding, so it is pinned here at the
        // smallest perturbation that is real. No tolerance, deliberately.
        const auto at = text.find("[814.9, 35.5, 225.6]");
        REQUIRE(at != std::string::npos);
        text.replace(at, std::string("[814.9, 35.5, 225.6]").size(), "[814.9, 35.5, 225.60002]");
        TestbedLayout nudged{};
        REQUIRE(load_text(text, nudged).ok);
        CHECK(digest(nudged) != digest(compiled));
    }
}

TEST_CASE("control: the loader reads every field it is responsible for") {
    // Coverage control. Load the asset twice: once into a default-built layout,
    // once into a layout pre-set to a DIFFERENT valid map (the forest stand,
    // which neutralizes every testbed feature). Any field the loader forgets to
    // assign keeps its pre-existing value, which differs between the two runs.
    // Without this, a forgotten field silently inherits the compiled default
    // and the equivalence case passes while proving nothing about it.
    //
    // A different valid layout rather than memset poison, for the same reason
    // the digest is not a memcmp: poison writes the padding too, and padding is
    // not a field.
    TestbedLayout from_default{};
    REQUIRE(world::load_layout_file(ASSET, from_default).ok);

    TestbedLayout from_forest = world::forest_stand_layout();
    // The two fields the asset deliberately does NOT carry, restored by hand:
    // crag.radius and crag.peak_height are NUMBERS rows (L0_BASE_RADIUS,
    // L0_RELIEF), i.e. registry rather than map, so the loader is right not to
    // read them. Restoring them keeps this control measuring the loader's
    // coverage of CONTENT instead of re-reporting a documented omission — and
    // note that it DID report it before this line existed, which is the
    // control working rather than a reason to weaken it.
    from_forest.crag.radius = from_default.crag.radius;
    from_forest.crag.peak_height = from_default.crag.peak_height;
    REQUIRE(world::load_layout_file(ASSET, from_forest).ok);

    CHECK(digest(from_default) == digest(from_forest));

    // ...and the control on the control: the two pre-states really were
    // different, so the check above is not comparing a layout with itself.
    CHECK(digest(TestbedLayout{}) != digest(world::forest_stand_layout()));
}

TEST_CASE("the loader refuses a map it cannot read rather than half-loading it") {
    TestbedLayout out{};

    SUBCASE("unknown key") {
        // The silent-default failure this strictness exists for: a mistyped key
        // would otherwise leave the engine's value in place and generate a
        // world quietly missing a feature.
        std::string text = read_asset();
        const auto at = text.find("\"rockline_frac\"");
        REQUIRE(at != std::string::npos);
        text.replace(at, std::string("\"rockline_frac\"").size(), "\"rockline_frak\"");
        const auto r = load_text(text, out);
        CHECK_FALSE(r.ok);
        INFO(r.error);
        CHECK(r.error.find("crag") != std::string::npos);
    }

    SUBCASE("missing key names its path") {
        const auto p = serialization::json_parse(R"({"stand":"Testbed","erosion":false})");
        REQUIRE(p.ok);
        const auto r = world::load_layout(p.root, out);
        CHECK_FALSE(r.ok);
        CHECK(r.error.find("crag") != std::string::npos);
    }

    SUBCASE("wrong type") {
        std::string text = read_asset();
        const auto at = text.find("\"pine_annulus_r0\": 140.0");
        REQUIRE(at != std::string::npos);
        text.replace(at, std::string("\"pine_annulus_r0\": 140.0").size(),
                     "\"pine_annulus_r0\": \"140\"");
        const auto r = load_text(text, out);
        CHECK_FALSE(r.ok);
        CHECK(r.error.find("pine_annulus_r0") != std::string::npos);
    }

    SUBCASE("unknown site kind") {
        std::string text = read_asset();
        const auto at = text.find("\"Hamlet\"");
        REQUIRE(at != std::string::npos);
        text.replace(at, std::string("\"Hamlet\"").size(), "\"Village\"");
        const auto r = load_text(text, out);
        CHECK_FALSE(r.ok);
        CHECK(r.error.find("Village") != std::string::npos);
    }

    SUBCASE("wrong site count") {
        std::string text = read_asset();
        const auto at = text.find("{ \"name\": \"Vaelmere\"");
        REQUIRE(at != std::string::npos);
        text.insert(at, "{ \"name\": \"extra\", \"position\": [1.0, 1.0], \"kind\": \"Shrine\" },\n    ");
        const auto r = load_text(text, out);
        CHECK_FALSE(r.ok);
        CHECK(r.error.find("sites") != std::string::npos);
    }

    SUBCASE("a missing file is an error, not an empty world") {
        const auto r = world::load_layout_file("games/daggerfall_n/assets/world/nope.json", out);
        CHECK_FALSE(r.ok);
        CHECK(r.error.find("cannot open") != std::string::npos);
    }
}
