/*
Created: 09:08:2026 - 10:48:00
Last updated: 09:08:2026 - 10:48:00
Module: engine/render
File: engine/render/sources/ProcTexture.h

Responsibility:
- Procedural texture generation (Q4в: textures are generated by code, no image
  files). Deterministic, tileable, low-color-count RGBA8 pixel buffers for the
  terrain/water materials, plus the 2x2 terrain atlas layout contract.

Key items:
- ProcTextureKind / ProcTextureDesc: the cache key (generation is pure).
- tileable_fbm(): periodic value-noise fBm — the shared noise primitive.
- generate_proc_texture(): one tileable RGBA8 texture, palette-quantized.
- generate_terrain_atlas(): grass|rock / sand|dirt in one 2x2 atlas (the
  terrain shader selects cells by splat weights — one bound texture, no
  contract change).

Dependencies:
- Uses: glm, C++ stdlib only. No GPU, no ECS, no platform includes.
- Used by: RenderSystem (upload via IRenderer::create_texture),
  tests/render/ProcTextureTests.cpp.

Notes:
- Determinism matters (Rule 13 spirit): integer-hash lattice noise only, no
  trigonometry-seeded hashes; same desc -> byte-identical pixels on every
  platform/compiler.
- Tileability: lattice coordinates wrap at `period`, so uv 0.0 and 1.0 sample
  the same lattice line — textures repeat seamlessly.
- Low color count: every texture quantizes its field to a small ramp
  (5-8 shades) so the image reads as a limited palette even before the
  optional palette post-process (Q9б).
- Colors here are look-dev values (stage-2 precedent: TerrainMesher tint), not
  gameplay constants; the design doc / art pass will refine them.

AI Agents Notice (must follow):
- Follow docs/ARCHITECTURE.md strictly.
- Keep generation pure and deterministic; covered by ProcTextureTests.
*/
/*
UPD:
- 09:08:2026 - 10:48:00: Stage 3 — initial procedural texture module.
*/

#pragma once

#include <cstdint>
#include <glm/vec2.hpp>
#include <vector>

namespace dfn::render {

enum class ProcTextureKind : uint8_t {
    GRASS = 0,
    ROCK = 1,
    SAND = 2,
    DIRT = 3,
    WATER = 4,
};

// Cache key for generated textures: generation is a pure function of this.
struct ProcTextureDesc {
    ProcTextureKind kind = ProcTextureKind::GRASS;
    uint32_t size = 128; // texels per side, power of two
    uint32_t seed = 1;
    [[nodiscard]] bool operator==(const ProcTextureDesc&) const = default;
};

// Deterministic periodic value-noise fBm in [0,1]. `uv` is the tile domain
// (0..1 spans one tile); the lattice wraps every `period` cells per axis, so
// f(uv + (1,0)) == f(uv) exactly. Octaves double the lattice period and halve
// the amplitude. Anisotropic periods (e.g. {8,3}) give streaked noise (water).
[[nodiscard]] float tileable_fbm(glm::vec2 uv, glm::ivec2 period, uint32_t seed,
                                 int octaves);

// Generates one tileable RGBA8 texture (size*size*4 bytes, row-major, alpha
// 255). Pure and deterministic: same desc -> identical bytes.
[[nodiscard]] std::vector<uint8_t> generate_proc_texture(const ProcTextureDesc& desc);

// The terrain splat atlas: a 2x2 grid of `cell_size` textures in one RGBA8
// image of side 2*cell_size. Layout contract with fs_terrain.sc:
//   (0,0) GRASS   (1,0) ROCK
//   (0,1) SAND    (1,1) DIRT
// (uv cell = kind_index -> {x: idx & 1, y: idx >> 1} * 0.5). Each cell tiles
// within itself; the shader wraps per-cell with fract().
[[nodiscard]] std::vector<uint8_t> generate_terrain_atlas(uint32_t cell_size,
                                                          uint32_t seed);

} // namespace dfn::render
