/*
Created: 09:08:2026 - 00:45:00
Last updated: 09:08:2026 - 11:57:20
Module: engine/platform/render
File: engine/platform/render/sources/bgfx/BgfxRenderer.cpp

Responsibility:
- BgfxRenderer implementation: the only translation unit that talks to bgfx.
  Scene renders into the low-res internal target; an integer-scaled,
  point-sampled quad blits it to the backbuffer (Q9); screenshots capture the
  final upscaled output (Rule 27).

Key items:
- BgfxRenderer::Impl (all bgfx state), embedded shader table (generated by the
  shaderc CMake step, Q50), create_bgfx_renderer().

Dependencies:
- Uses: bgfx, generated shader headers (build tree, shaders_gen/), BgfxCallback.
- Used by: dfn_platform_render target.

AI Agents Notice (must follow):
- Follow docs/ARCHITECTURE.md strictly.
- macOS/Metal is the tested path this stage; other platforms compile-clean via
  the auto renderer type but are untested.
- Culling is OFF this stage (flat terrain, safety for the Q51 tour); revisit
  with real scenes at stage 3.
*/
/*
UPD:
- 09:08:2026 - 00:45:00: Stage 2 — initial implementation (Metal, internal
  target + integer upscale, embedded shaders, screenshot scheduling).
- 09:08:2026 - 10:56:00: Stage 3 — RenderEnvironment -> u_envParams uniforms,
  backend sky pass (sequential scene view), palette post in the upscale pass
  (Q9b, RendererInitParams::palette_post), "water" logical name -> alpha-blend
  state, point-sampled material textures.
- 09:08:2026 - 11:57:20: Stage 3b — "prop" logical program (vs_terrain +
  fs_prop: vertex-color albedo, lambert + fog) for placeholder scatter/site
  meshes.
*/

#include "engine/platform/render/sources/bgfx/BgfxRenderer.h"

#include "engine/platform/render/sources/bgfx/BgfxCallback.h"
#include "engine/platform/render/sources/bgfx/BgfxPalette.h"
#include "engine/platform/render/sources/bgfx/CreateBgfxRenderer.h"

#include <bgfx/bgfx.h>
#include <glm/gtc/type_ptr.hpp>

#include <algorithm>
#include <array>
#include <cstdio>
#include <cstring>
#include <string>
#include <unordered_map>
#include <vector>

// Embedded compiled shaders (generated into <build>/shaders_gen by the shaderc
// custom commands in this layer's CMakeLists — Q50).
#if defined(__APPLE__)
#include <vs_terrain_mtl.h>
#include <fs_terrain_mtl.h>
#include <vs_unlit_mtl.h>
#include <fs_unlit_mtl.h>
#include <vs_debug_mtl.h>
#include <fs_debug_mtl.h>
#include <vs_upscale_mtl.h>
#include <fs_upscale_mtl.h>
#include <vs_sky_mtl.h>
#include <fs_sky_mtl.h>
#include <vs_water_mtl.h>
#include <fs_water_mtl.h>
#include <fs_prop_mtl.h>
#endif

namespace dfn::platform {

namespace {

constexpr bgfx::ViewId VIEW_SCENE = 0;         // -> internal low-res target
constexpr bgfx::ViewId VIEW_BACKBUFFER = 1;    // clear (letterbox black)
constexpr bgfx::ViewId VIEW_UPSCALE = 2;       // integer-scaled quad

// Look-dev clear color (sky), not a gameplay constant: light steppe-sky blue.
constexpr uint32_t SKY_COLOR_RGBA = 0x87b5e0ff;

struct ShaderBlob {
    const uint8_t* data = nullptr;
    uint32_t size = 0;
};
struct ProgramSource {
    const char* name;
    ShaderBlob vs;
    ShaderBlob fs;
};

#if defined(__APPLE__)
const ProgramSource PROGRAM_TABLE[] = {
    {"terrain", {vs_terrain_mtl, sizeof(vs_terrain_mtl)},
                {fs_terrain_mtl, sizeof(fs_terrain_mtl)}},
    {"unlit",   {vs_unlit_mtl, sizeof(vs_unlit_mtl)},
                {fs_unlit_mtl, sizeof(fs_unlit_mtl)}},
    {"debug",   {vs_debug_mtl, sizeof(vs_debug_mtl)},
                {fs_debug_mtl, sizeof(fs_debug_mtl)}},
    {"upscale", {vs_upscale_mtl, sizeof(vs_upscale_mtl)},
                {fs_upscale_mtl, sizeof(fs_upscale_mtl)}},
    {"sky",     {vs_sky_mtl, sizeof(vs_sky_mtl)},
                {fs_sky_mtl, sizeof(fs_sky_mtl)}},
    {"water",   {vs_water_mtl, sizeof(vs_water_mtl)},
                {fs_water_mtl, sizeof(fs_water_mtl)}},
    // "prop" shares the terrain vertex stage (world pos + normal + color
    // pass-through); only the fragment differs (vertex-color albedo).
    {"prop",    {vs_terrain_mtl, sizeof(vs_terrain_mtl)},
                {fs_prop_mtl, sizeof(fs_prop_mtl)}},
};
#else
// Non-Apple platforms compile clean but ship no embedded shaders this stage
// (macOS focus per the stage-2 brief); load_program returns invalid handles.
const ProgramSource PROGRAM_TABLE[] = {
    {"terrain", {}, {}}, {"unlit", {}, {}}, {"debug", {}, {}},
    {"upscale", {}, {}}, {"sky", {}, {}}, {"water", {}, {}}, {"prop", {}, {}},
};
#endif

// Logical program names rendered with alpha blend + read-only depth (the
// name -> render-state convention acknowledged at the stage-3 sync).
constexpr const char* TRANSPARENT_PROGRAMS[] = {"water"};

constexpr uint16_t ENV_PARAM_VEC4S = 11; // layout contract with dfn_env.sh
constexpr uint16_t PALETTE_SIZE = 64;

struct DebugVertex {
    float x, y, z;
    uint32_t abgr;
};

struct UpscaleVertex {
    float x, y, z;
    float u, v;
};

// Fullscreen quad in clip space; v flipped so the internal target reads
// upright on Metal/D3D-style render-to-texture orientation.
const UpscaleVertex UPSCALE_QUAD_VERTICES[] = {
    {-1.0f, -1.0f, 0.0f, 0.0f, 1.0f},
    { 1.0f, -1.0f, 0.0f, 1.0f, 1.0f},
    {-1.0f,  1.0f, 0.0f, 0.0f, 0.0f},
    { 1.0f,  1.0f, 0.0f, 1.0f, 0.0f},
};
const uint16_t UPSCALE_QUAD_INDICES[] = {0, 1, 2, 1, 3, 2};

} // namespace

struct BgfxRenderer::Impl {
    BgfxCallback callback;
    bool initialized = false;

    uint32_t fb_width = 0;
    uint32_t fb_height = 0;
    uint32_t internal_width = 0;
    uint32_t internal_height = 0;
    uint32_t reset_flags = BGFX_RESET_NONE;

    bgfx::VertexLayout mesh_layout;
    bgfx::VertexLayout debug_layout;
    bgfx::VertexLayout upscale_layout;

    bgfx::FrameBufferHandle internal_fb = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle s_tex_color = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_params = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_env_params = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_post_params = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_palette = BGFX_INVALID_HANDLE;
    bgfx::VertexBufferHandle quad_vb = BGFX_INVALID_HANDLE;
    bgfx::IndexBufferHandle quad_ib = BGFX_INVALID_HANDLE;
    bgfx::ProgramHandle upscale_program = BGFX_INVALID_HANDLE;
    bgfx::ProgramHandle debug_program = BGFX_INVALID_HANDLE;
    bgfx::ProgramHandle sky_program = BGFX_INVALID_HANDLE;

    RenderEnvironment environment;                 // last set_environment (defaults valid)
    std::array<glm::vec4, 64> palette{};           // fixed palette (Q9b)
    bool palette_post = false;

    struct MeshRes {
        bgfx::VertexBufferHandle vb;
        bgfx::IndexBufferHandle ib;
    };
    std::unordered_map<uint32_t, MeshRes> meshes;
    std::unordered_map<uint32_t, bgfx::TextureHandle> textures;
    std::unordered_map<uint32_t, bgfx::ProgramHandle> programs;
    std::unordered_map<uint32_t, bool> transparent; // program id -> water-style state
    uint32_t next_id = 1;

    std::vector<DebugVertex> debug_lines; // flushed each end_frame
    std::string pending_screenshot;       // scheduled into the next end_frame
    bool in_frame = false;

    [[nodiscard]] bgfx::ProgramHandle make_program(const char* name) const {
        for (const ProgramSource& src : PROGRAM_TABLE) {
            if (std::strcmp(src.name, name) == 0 && src.vs.data != nullptr) {
                const bgfx::ShaderHandle vs =
                    bgfx::createShader(bgfx::makeRef(src.vs.data, src.vs.size));
                const bgfx::ShaderHandle fs =
                    bgfx::createShader(bgfx::makeRef(src.fs.data, src.fs.size));
                return bgfx::createProgram(vs, fs, true /* destroy shaders */);
            }
        }
        std::fprintf(stderr, "[render] unknown shader program: %s\n", name);
        return BGFX_INVALID_HANDLE;
    }

    // Packs the cached RenderEnvironment into u_envParams; the index layout is
    // the dfn_env.sh contract. Called once per frame in begin_frame — uniform
    // values persist across submits within the frame.
    void apply_environment() const {
        const RenderEnvironment& e = environment;
        glm::vec4 packed[ENV_PARAM_VEC4S] = {
            {e.sun_direction, 0.0f},
            {e.sun_color, 0.0f},
            {e.ambient_color, 0.0f},
            {e.fog_color, 0.0f},
            {e.fog_start_m, e.fog_end_m, e.time_seconds, 0.0f},
            {e.sky_zenith_color, 0.0f},
            {e.sky_horizon_color, 0.0f},
            {e.sand_height_m, e.sand_blend_m, e.rock_slope_start, e.rock_slope_end},
            {e.terrain_tiles_per_chunk, 0.0f, 0.0f, 0.0f},
            e.water_color,
            {e.water_scroll_uv, 0.0f, 0.0f},
        };
        bgfx::setUniform(u_env_params, packed, ENV_PARAM_VEC4S);
    }

    // Largest integer factor of the internal target fitting the framebuffer,
    // centered; never zero (Q9).
    void dest_rect(uint32_t& x, uint32_t& y, uint32_t& w, uint32_t& h) const {
        const uint32_t fx = internal_width > 0 ? fb_width / internal_width : 1;
        const uint32_t fy = internal_height > 0 ? fb_height / internal_height : 1;
        const uint32_t factor = std::max(1u, std::min(fx, fy));
        w = std::min(internal_width * factor, fb_width);
        h = std::min(internal_height * factor, fb_height);
        x = (fb_width - w) / 2;
        y = (fb_height - h) / 2;
    }
};

BgfxRenderer::BgfxRenderer() : impl_(std::make_unique<Impl>()) {}

BgfxRenderer::~BgfxRenderer() {
    shutdown();
}

bool BgfxRenderer::init(const RendererInitParams& params) {
    Impl& im = *impl_;
    if (im.initialized) {
        return false;
    }
    if (params.native_window_handle == nullptr) {
        std::fprintf(stderr,
                     "[render] bgfx backend needs a native window handle "
                     "(use the null renderer for headless runs)\n");
        return false;
    }

    im.fb_width = params.framebuffer_width;
    im.fb_height = params.framebuffer_height;
    im.internal_width = params.internal_width > 0 ? params.internal_width
                                                  : params.framebuffer_width;
    im.internal_height = params.internal_height > 0 ? params.internal_height
                                                    : params.framebuffer_height;
    im.reset_flags = params.vsync ? BGFX_RESET_VSYNC : BGFX_RESET_NONE;

    bgfx::renderFrame(); // single-threaded mode: render on this thread

    bgfx::Init init;
#if defined(__APPLE__)
    init.type = bgfx::RendererType::Metal;
#else
    init.type = bgfx::RendererType::Count; // auto-pick (untested this stage)
#endif
    init.platformData.nwh = params.native_window_handle;
    init.resolution.width = im.fb_width;
    init.resolution.height = im.fb_height;
    init.resolution.reset = im.reset_flags;
    init.callback = &im.callback;
    if (!bgfx::init(init)) {
        std::fprintf(stderr, "[render] bgfx::init failed\n");
        return false;
    }

    im.mesh_layout.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Normal, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();
    im.debug_layout.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();
    im.upscale_layout.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
        .end();

    // Internal low-res target: point-sampled color + write-only depth (Q9).
    const uint64_t color_flags = BGFX_TEXTURE_RT | BGFX_SAMPLER_MIN_POINT
                               | BGFX_SAMPLER_MAG_POINT | BGFX_SAMPLER_MIP_POINT
                               | BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP;
    const bgfx::TextureHandle color = bgfx::createTexture2D(
        static_cast<uint16_t>(im.internal_width),
        static_cast<uint16_t>(im.internal_height), false, 1,
        bgfx::TextureFormat::RGBA8, color_flags);
    const bgfx::TextureHandle depth = bgfx::createTexture2D(
        static_cast<uint16_t>(im.internal_width),
        static_cast<uint16_t>(im.internal_height), false, 1,
        bgfx::TextureFormat::D24S8, BGFX_TEXTURE_RT_WRITE_ONLY);
    const bgfx::TextureHandle attachments[] = {color, depth};
    im.internal_fb = bgfx::createFrameBuffer(2, attachments, true);

    im.s_tex_color = bgfx::createUniform("s_texColor", bgfx::UniformType::Sampler);
    im.u_params = bgfx::createUniform("u_params", bgfx::UniformType::Vec4);
    im.u_env_params =
        bgfx::createUniform("u_envParams", bgfx::UniformType::Vec4, ENV_PARAM_VEC4S);
    im.u_post_params = bgfx::createUniform("u_postParams", bgfx::UniformType::Vec4);
    im.u_palette =
        bgfx::createUniform("u_palette", bgfx::UniformType::Vec4, PALETTE_SIZE);
    im.quad_vb = bgfx::createVertexBuffer(
        bgfx::makeRef(UPSCALE_QUAD_VERTICES, sizeof(UPSCALE_QUAD_VERTICES)),
        im.upscale_layout);
    im.quad_ib = bgfx::createIndexBuffer(
        bgfx::makeRef(UPSCALE_QUAD_INDICES, sizeof(UPSCALE_QUAD_INDICES)));
    im.upscale_program = im.make_program("upscale");
    im.debug_program = im.make_program("debug");
    im.sky_program = im.make_program("sky");

    // Sequential scene view (stage 3): sky first (backend), then the caller's
    // opaque submits, then transparents (RenderSystem orders them), then debug
    // lines in end_frame. Depth testing still resolves opaque occlusion.
    bgfx::setViewMode(VIEW_SCENE, bgfx::ViewMode::Sequential);

    im.palette_post = params.palette_post;
    im.palette = build_dfn_palette();

    im.initialized = true;
    return true;
}

void BgfxRenderer::shutdown() {
    Impl& im = *impl_;
    if (!im.initialized) {
        return;
    }
    for (auto& [id, mesh] : im.meshes) {
        bgfx::destroy(mesh.vb);
        bgfx::destroy(mesh.ib);
    }
    im.meshes.clear();
    for (auto& [id, tex] : im.textures) {
        bgfx::destroy(tex);
    }
    im.textures.clear();
    for (auto& [id, prog] : im.programs) {
        bgfx::destroy(prog);
    }
    im.programs.clear();
    if (bgfx::isValid(im.upscale_program)) bgfx::destroy(im.upscale_program);
    if (bgfx::isValid(im.debug_program)) bgfx::destroy(im.debug_program);
    if (bgfx::isValid(im.sky_program)) bgfx::destroy(im.sky_program);
    if (bgfx::isValid(im.quad_ib)) bgfx::destroy(im.quad_ib);
    if (bgfx::isValid(im.quad_vb)) bgfx::destroy(im.quad_vb);
    if (bgfx::isValid(im.u_params)) bgfx::destroy(im.u_params);
    if (bgfx::isValid(im.u_env_params)) bgfx::destroy(im.u_env_params);
    if (bgfx::isValid(im.u_post_params)) bgfx::destroy(im.u_post_params);
    if (bgfx::isValid(im.u_palette)) bgfx::destroy(im.u_palette);
    if (bgfx::isValid(im.s_tex_color)) bgfx::destroy(im.s_tex_color);
    if (bgfx::isValid(im.internal_fb)) bgfx::destroy(im.internal_fb);
    bgfx::frame(); // flush destroys (and any pending screenshot write)
    bgfx::shutdown();
    im.initialized = false;
}

void BgfxRenderer::resize(uint32_t framebuffer_width, uint32_t framebuffer_height) {
    Impl& im = *impl_;
    if (!im.initialized || framebuffer_width == 0 || framebuffer_height == 0) {
        return;
    }
    im.fb_width = framebuffer_width;
    im.fb_height = framebuffer_height;
    bgfx::reset(framebuffer_width, framebuffer_height, im.reset_flags);
    // The internal target is resolution-independent (Q9): only the upscale
    // rect changes, and it is recomputed every end_frame.
}

void BgfxRenderer::begin_frame(const glm::mat4& view, const glm::mat4& proj) {
    Impl& im = *impl_;
    if (!im.initialized) {
        return;
    }
    im.in_frame = true;
    bgfx::setViewFrameBuffer(VIEW_SCENE, im.internal_fb);
    bgfx::setViewRect(VIEW_SCENE, 0, 0, static_cast<uint16_t>(im.internal_width),
                      static_cast<uint16_t>(im.internal_height));
    bgfx::setViewClear(VIEW_SCENE, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH,
                       SKY_COLOR_RGBA, 1.0f, 0);
    bgfx::setViewTransform(VIEW_SCENE, glm::value_ptr(view), glm::value_ptr(proj));
    bgfx::touch(VIEW_SCENE); // clear even on an empty frame

    // Frame environment (cached; struct defaults are valid pre-first-set).
    im.apply_environment();

    // Sky background: fullscreen quad, no depth test/write; everything solid
    // draws over it (sequential view — this is always the first draw).
    if (bgfx::isValid(im.sky_program)) {
        bgfx::setVertexBuffer(0, im.quad_vb);
        bgfx::setIndexBuffer(im.quad_ib);
        bgfx::setState(BGFX_STATE_WRITE_RGB);
        bgfx::submit(VIEW_SCENE, im.sky_program);
    }
}

void BgfxRenderer::set_environment(const RenderEnvironment& env) {
    impl_->environment = env;
    // Uniforms are (re)applied at the next begin_frame; if we are mid-frame,
    // update them now so this frame's remaining submits see the new values.
    if (impl_->initialized && impl_->in_frame) {
        impl_->apply_environment();
    }
}

void BgfxRenderer::end_frame() {
    Impl& im = *impl_;
    if (!im.initialized || !im.in_frame) {
        return;
    }

    // One-frame debug lines (accumulated by debug_line).
    if (!im.debug_lines.empty() && bgfx::isValid(im.debug_program)) {
        const auto count = static_cast<uint32_t>(im.debug_lines.size());
        if (bgfx::getAvailTransientVertexBuffer(count, im.debug_layout) >= count) {
            bgfx::TransientVertexBuffer tvb;
            bgfx::allocTransientVertexBuffer(&tvb, count, im.debug_layout);
            std::memcpy(tvb.data, im.debug_lines.data(), count * sizeof(DebugVertex));
            bgfx::setVertexBuffer(0, &tvb, 0, count);
            bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A
                           | BGFX_STATE_WRITE_Z | BGFX_STATE_DEPTH_TEST_LESS
                           | BGFX_STATE_PT_LINES);
            bgfx::submit(VIEW_SCENE, im.debug_program);
        }
    }
    im.debug_lines.clear();

    // Letterbox clear, then the integer-scaled point-sampled upscale (Q9).
    bgfx::setViewFrameBuffer(VIEW_BACKBUFFER, BGFX_INVALID_HANDLE);
    bgfx::setViewRect(VIEW_BACKBUFFER, 0, 0, static_cast<uint16_t>(im.fb_width),
                      static_cast<uint16_t>(im.fb_height));
    bgfx::setViewClear(VIEW_BACKBUFFER, BGFX_CLEAR_COLOR, 0x000000ff, 1.0f, 0);
    bgfx::touch(VIEW_BACKBUFFER);

    if (bgfx::isValid(im.upscale_program)) {
        uint32_t dx = 0;
        uint32_t dy = 0;
        uint32_t dw = 0;
        uint32_t dh = 0;
        im.dest_rect(dx, dy, dw, dh);
        bgfx::setViewFrameBuffer(VIEW_UPSCALE, BGFX_INVALID_HANDLE);
        bgfx::setViewRect(VIEW_UPSCALE, static_cast<uint16_t>(dx),
                          static_cast<uint16_t>(dy), static_cast<uint16_t>(dw),
                          static_cast<uint16_t>(dh));
        const float post[4] = {im.palette_post ? 1.0f : 0.0f,
                               static_cast<float>(PALETTE_SIZE),
                               static_cast<float>(im.internal_width),
                               static_cast<float>(im.internal_height)};
        bgfx::setUniform(im.u_post_params, post);
        if (im.palette_post) {
            bgfx::setUniform(im.u_palette, im.palette.data(), PALETTE_SIZE);
        }
        bgfx::setTexture(0, im.s_tex_color, bgfx::getTexture(im.internal_fb, 0));
        bgfx::setVertexBuffer(0, im.quad_vb);
        bgfx::setIndexBuffer(im.quad_ib);
        bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A);
        bgfx::submit(VIEW_UPSCALE, im.upscale_program);
    }

    if (!im.pending_screenshot.empty()) {
        bgfx::requestScreenShot(BGFX_INVALID_HANDLE, im.pending_screenshot.c_str());
        im.pending_screenshot.clear();
    }

    bgfx::frame();
    im.in_frame = false;
}

MeshHandle BgfxRenderer::create_mesh(std::span<const Vertex> vertices,
                                     std::span<const uint32_t> indices) {
    Impl& im = *impl_;
    if (!im.initialized || vertices.empty() || indices.empty()) {
        return {};
    }
    const bgfx::Memory* vmem = bgfx::copy(
        vertices.data(), static_cast<uint32_t>(vertices.size_bytes()));
    const bgfx::Memory* imem = bgfx::copy(
        indices.data(), static_cast<uint32_t>(indices.size_bytes()));
    Impl::MeshRes res{
        bgfx::createVertexBuffer(vmem, im.mesh_layout),
        bgfx::createIndexBuffer(imem, BGFX_BUFFER_INDEX32),
    };
    const uint32_t id = im.next_id++;
    im.meshes.emplace(id, res);
    return MeshHandle{id};
}

void BgfxRenderer::destroy_mesh(MeshHandle mesh) {
    Impl& im = *impl_;
    const auto it = im.meshes.find(mesh.id);
    if (it != im.meshes.end()) {
        bgfx::destroy(it->second.vb);
        bgfx::destroy(it->second.ib);
        im.meshes.erase(it);
    }
}

TextureHandle BgfxRenderer::create_texture(uint32_t width, uint32_t height,
                                           TextureFormat format,
                                           std::span<const uint8_t> pixels) {
    Impl& im = *impl_;
    if (!im.initialized || width == 0 || height == 0 || pixels.empty()) {
        return {};
    }
    const bgfx::TextureFormat::Enum fmt = format == TextureFormat::RGBA8
                                              ? bgfx::TextureFormat::RGBA8
                                              : bgfx::TextureFormat::R8;
    const bgfx::Memory* mem =
        bgfx::copy(pixels.data(), static_cast<uint32_t>(pixels.size_bytes()));
    const bgfx::TextureHandle tex = bgfx::createTexture2D(
        static_cast<uint16_t>(width), static_cast<uint16_t>(height), false, 1, fmt,
        BGFX_TEXTURE_NONE, mem);
    if (!bgfx::isValid(tex)) {
        return {};
    }
    const uint32_t id = im.next_id++;
    im.textures.emplace(id, tex);
    return TextureHandle{id};
}

void BgfxRenderer::destroy_texture(TextureHandle texture) {
    Impl& im = *impl_;
    const auto it = im.textures.find(texture.id);
    if (it != im.textures.end()) {
        bgfx::destroy(it->second);
        im.textures.erase(it);
    }
}

ProgramHandle BgfxRenderer::load_program(std::string_view name) {
    Impl& im = *impl_;
    if (!im.initialized) {
        return {};
    }
    const bgfx::ProgramHandle prog = im.make_program(std::string(name).c_str());
    if (!bgfx::isValid(prog)) {
        return {};
    }
    const uint32_t id = im.next_id++;
    im.programs.emplace(id, prog);
    for (const char* transparent_name : TRANSPARENT_PROGRAMS) {
        if (name == transparent_name) {
            im.transparent.emplace(id, true);
        }
    }
    return ProgramHandle{id};
}

void BgfxRenderer::destroy_program(ProgramHandle program) {
    Impl& im = *impl_;
    const auto it = im.programs.find(program.id);
    if (it != im.programs.end()) {
        bgfx::destroy(it->second);
        im.programs.erase(it);
    }
    im.transparent.erase(program.id);
}

void BgfxRenderer::submit(MeshHandle mesh, ProgramHandle program,
                          const glm::mat4& transform, TextureHandle texture) {
    Impl& im = *impl_;
    if (!im.initialized || !im.in_frame) {
        return;
    }
    const auto mesh_it = im.meshes.find(mesh.id);
    const auto prog_it = im.programs.find(program.id);
    if (mesh_it == im.meshes.end() || prog_it == im.programs.end()) {
        return;
    }
    bgfx::setTransform(glm::value_ptr(transform));
    bgfx::setVertexBuffer(0, mesh_it->second.vb);
    bgfx::setIndexBuffer(mesh_it->second.ib);

    float params[4] = {0.0f, 0.0f, 0.0f, 0.0f};
    const auto tex_it = im.textures.find(texture.id);
    if (tex_it != im.textures.end()) {
        // Point-sampled material textures: Daggerfall crunch, and no bleed
        // across the terrain atlas cells (stage-3 sync, informational item).
        bgfx::setTexture(0, im.s_tex_color, tex_it->second,
                         BGFX_SAMPLER_MIN_POINT | BGFX_SAMPLER_MAG_POINT
                             | BGFX_SAMPLER_MIP_POINT);
        params[0] = 1.0f;
    }
    bgfx::setUniform(im.u_params, params);

    // Culling deliberately off this stage (see header notice). Transparent
    // programs ("water"): alpha blend, depth read-only, drawn after opaques
    // by the caller (sequential view).
    const bool is_transparent = im.transparent.contains(program.id);
    const uint64_t state =
        is_transparent
            ? (BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A
               | BGFX_STATE_DEPTH_TEST_LESS | BGFX_STATE_BLEND_ALPHA)
            : (BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_WRITE_Z
               | BGFX_STATE_DEPTH_TEST_LESS);
    bgfx::setState(state);
    bgfx::submit(VIEW_SCENE, prog_it->second);
}

void BgfxRenderer::debug_line(const glm::vec3& from, const glm::vec3& to,
                              uint32_t color_rgba) {
#if defined(NDEBUG)
    (void)from;
    (void)to;
    (void)color_rgba;
#else
    impl_->debug_lines.push_back({from.x, from.y, from.z, color_rgba});
    impl_->debug_lines.push_back({to.x, to.y, to.z, color_rgba});
#endif
}

bool BgfxRenderer::save_screenshot(const std::string& path) {
    Impl& im = *impl_;
    if (!im.initialized) {
        return false;
    }
    // Scheduled into the next end_frame (bgfx captures during frame
    // processing); the Tour renders flush frames after scheduling.
    im.pending_screenshot = path;
    return true;
}

void BgfxRenderer::reload_shaders() {
    // Debug no-op this stage: shaders are embedded at build time. Disk-based
    // hot-reload (Q50) arrives with the stage-3 material work.
}

std::unique_ptr<IRenderer> create_bgfx_renderer() {
    return std::make_unique<BgfxRenderer>();
}

} // namespace dfn::platform
