/*
Created: 09:08:2026 - 00:45:00
Last updated: 10:08:2026 - 23:32:21
Module: engine/platform/render
File: engine/platform/render/sources/bgfx/BgfxRenderer.cpp

Responsibility:
- BgfxRenderer LIFECYCLE: init (bgfx bring-up, targets, uniforms, shadow
  resources), shutdown (guarded destroys + the mesh-budget report), resize,
  and the embedded shader table (generated by the shaderc CMake step, Q50).
  One of four translation units over BgfxRendererImpl.h (Rule 21 split);
  the frame path is BgfxRendererFrame.cpp, draws BgfxRendererSubmit.cpp,
  handle bookkeeping BgfxRendererResources.cpp.

Key items:
- PROGRAM_TABLE (embedded shaders), Impl::make_program, BgfxRenderer::init /
  shutdown / resize, create_bgfx_renderer().

Dependencies:
- Uses: BgfxRendererImpl.h, bgfx, generated shader headers (shaders_gen/).
- Used by: dfn_platform_render target.

AI Agents Notice (must follow):
- Follow docs/ARCHITECTURE.md strictly.
- macOS/Metal is the tested path this stage; other platforms compile-clean via
  the auto renderer type but are untested.
- Culling is OFF this stage (flat terrain, safety for the Q51 tour); revisit
  with real scenes at stage 3.
*/
/*
UPD:
- 09:08:2026 - 00:45:00: Stage 2 — initial implementation (Metal, internal
  target + integer upscale, embedded shaders, screenshot scheduling).
- 09:08:2026 - 10:56:00: Stage 3 — RenderEnvironment -> u_envParams uniforms,
  backend sky pass (sequential scene view), palette post in the upscale pass
  (Q9b, RendererInitParams::palette_post), "water" logical name -> alpha-blend
  state, point-sampled material textures.
- 09:08:2026 - 11:57:20: Stage 3b — "prop" logical program (vs_terrain +
  fs_prop: vertex-color albedo, lambert + fog) for placeholder scatter/site
  meshes.
- 09:08:2026 - 14:11:37: Dynamic sun shadows (user decision в1): depth-only
  shadow view (2048 map over the loaded chunk ring, eye-centered ortho from
  environment.sun_direction, texel-snapped), opaque submits also render into
  it with the internal "shadow" program; terrain/prop sample it with one hard
  compare tap (dfn_shadow.sh). Shadows follow the app-animated sun (в2) and
  switch off below SHADOW_MIN_SUN_ELEVATION (night: ambient only).
- 09:08:2026 - 18:40:00: Thin casters cast nothing (user bug: tree trunks had
  no shadow, only the canopy). Root cause was shadow-map TEXEL DENSITY, not a
  missed submit path — trunk and crown are the same vertices in the same
  batched draw, so the shadow pass never had a way to skip one. 0.625 m per
  texel could not represent a 0.28-1.1 m trunk. Shadow map 2048 -> 4096 and
  half extent 640 -> 320 m => 0.156 m per texel (and the normal offset, which
  is defined in texels, shrinks with it). Covers the §6.2 standing stones too.
- 09:08:2026 - 19:26:00: Day/night (в1/в2): env uniform block 11 -> 15 vec4s
  carrying moon direction/phase/colour/light, star intensity and the carried
  point light; sky shader gains stars and a phased moon disc; terrain and
  props light through the shared dfn_surface_light().
- 09:08:2026 - 19:32:00: Light ARRAY (8 lit, cube-shadow casters to come with
  interiors) + authored ambient_darkness; env block 15 -> 32 vec4s. REVERSED-Z
  depth (D32F internal target, clear 0, DEPTH_TEST_GREATER, projection flipped
  in begin_frame) so CAMERA_FAR 8000 m does not z-fight distant landmarks.
- 09:08:2026 - 20:02:00: Foliage material path: "foliage" alpha-cutout program
  (albedo from the leaf mask, vertex colour repurposed to wind data) and the
  internal "shadow_cutout" caster so the canopy's shadow gets the mask's
  holes and the same sway; wind packed at env slot [32].
- 09:08:2026 - 20:40:00: INTERIOR LIGHTING — carried lights now CAST. Cube
  shadows for up to MAX_SHADOW_POINT_LIGHTS lights: six 90-degree faces per
  light packed into ONE 2D atlas (4x3 tiles of 512 px) storing linear distance
  / radius, twelve views ahead of the scene view, and the "point_shadow"
  caster program. Casters are culled to the light SPHERE and then per FACE,
  which is what keeps a torch affordable; the sphere test uses per-mesh bounds
  measured in create_mesh (IRenderer::submit carries no bounds and that
  contract is frozen — so the one place that already has the vertices keeps
  them). Lights are reordered so shadow casters occupy the first slots, which
  makes the shader's light index the cube index by construction.
- 09:08:2026 - 22:23:29: SUN CASTER CULL. `submit` now rejects a draw's depth
  pass when its world bounding sphere lies wholly outside the shadow ortho
  volume (light-space slab test against SHADOW_HALF_EXTENT_M /
  SHADOW_DEPTH_HALF_M). Verified by A/B with an inverted-cull control.
- 09:08:2026 - 23:50:06: CRASH FIX (user report: segfault on exit). create_mesh
  never validated bgfx's handles: on pool exhaustion createVertexBuffer returns
  BGFX_INVALID_HANDLE (idx 0xFFFF), that was stored in the mesh record and
  handed back as a VALID engine handle (MeshHandle validity is "our id != 0"),
  and shutdown then called bgfx::destroy on it — which in a release build skips
  its assert and indexes m_vertexBufferRef[0xFFFF], the reported stack exactly.
  Now: a failed create is refused and reported, every destroy is guarded, and
  live/peak/created/destroyed mesh handles are counted so the budget cliff is
  reported BEFORE it is walked off. Added the "overlay" program (unlit shaders,
  alpha blend) for the HUD layer.
- 10:08:2026 - 01:47:53: Rule 21 split (the file was 1424 lines against the
  800 ceiling). Impl moved to BgfxRendererImpl.h; this file keeps lifecycle +
  the embedded shader table; frame pass, submit and handle bookkeeping moved
  to BgfxRendererFrame/Submit/Resources.cpp. Code moved VERBATIM — no
  behaviour change (control: identical mesh-handle counts on the same tour).
- 10:08:2026 - 23:24:48: COVERAGE ANTIALIASING ON THE INTERNAL TARGET — the
  user's oldest complaint («при беге трясет», «всё дергает и перерисовывается
  очень рябью»). MSAA 4x on the internal colour+depth target (DFN_MSAA=0|2|4|8),
  an alpha-weighted mip chain for cutout MASKS only, and
  BGFX_STATE_BLEND_ALPHA_TO_COVERAGE on the cutout path. Measured, one 0.05 m
  stride at RUN_SPEED, DFN_WIND_FREEZE=120, 640x360, palette off, control
  0.000 %: near canopy 0.864 -> 0.621 %, treeline 0.094 -> 0.004 %. MSAA ALONE
  IS WORTH ALMOST NOTHING (0.819 / 0.080) and MSAA 8x equals 4x to three
  digits — the residual pixels are not partially covered, they are written or
  discarded, so the fix had to reach the MASK. Details and the palette-on
  numbers in docs/specs/render.md.
- 10:08:2026 - 23:32:21: Число выборок берётся из параметров запуска, DFN_MSAA остаётся перекрытием для инструментов. Врезка лида в одну строку: оставить настройку неподключённой значило бы отгрузить немой ноль ровно того класса, который этот файл сегодня и чинил.
*/

#include "engine/platform/render/sources/bgfx/BgfxRendererImpl.h"

#include "engine/platform/render/sources/bgfx/BgfxPalette.h"
#include "engine/platform/render/sources/bgfx/CreateBgfxRenderer.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>

// Embedded compiled shaders (generated into <build>/shaders_gen by the shaderc
// custom commands in this layer's CMakeLists — Q50).
#if defined(__APPLE__)
#include <vs_terrain_mtl.h>
#include <fs_terrain_mtl.h>
#include <vs_unlit_mtl.h>
#include <fs_unlit_mtl.h>
#include <vs_debug_mtl.h>
#include <fs_debug_mtl.h>
#include <vs_upscale_mtl.h>
#include <fs_upscale_mtl.h>
#include <vs_sky_mtl.h>
#include <fs_sky_mtl.h>
#include <vs_water_mtl.h>
#include <fs_water_mtl.h>
#include <fs_prop_mtl.h>
#include <fs_path_mtl.h>
#include <vs_shadow_mtl.h>
#include <fs_shadow_mtl.h>
#include <vs_foliage_mtl.h>
#include <fs_foliage_mtl.h>
#include <vs_shadow_cutout_mtl.h>
#include <fs_shadow_cutout_mtl.h>
#include <vs_point_shadow_mtl.h>
#include <fs_point_shadow_mtl.h>
#endif

namespace dfn::platform {

namespace {

struct ShaderBlob {
    const uint8_t* data = nullptr;
    uint32_t size = 0;
};
struct ProgramSource {
    const char* name;
    ShaderBlob vs;
    ShaderBlob fs;
};

#if defined(__APPLE__)
const ProgramSource PROGRAM_TABLE[] = {
    {"terrain", {vs_terrain_mtl, sizeof(vs_terrain_mtl)},
                {fs_terrain_mtl, sizeof(fs_terrain_mtl)}},
    {"unlit",   {vs_unlit_mtl, sizeof(vs_unlit_mtl)},
                {fs_unlit_mtl, sizeof(fs_unlit_mtl)}},
    {"foliage", {vs_foliage_mtl, sizeof(vs_foliage_mtl)},
                {fs_foliage_mtl, sizeof(fs_foliage_mtl)}},
    {"shadow_cutout", {vs_shadow_cutout_mtl, sizeof(vs_shadow_cutout_mtl)},
                {fs_shadow_cutout_mtl, sizeof(fs_shadow_cutout_mtl)}},
    {"debug",   {vs_debug_mtl, sizeof(vs_debug_mtl)},
                {fs_debug_mtl, sizeof(fs_debug_mtl)}},
    {"upscale", {vs_upscale_mtl, sizeof(vs_upscale_mtl)},
                {fs_upscale_mtl, sizeof(fs_upscale_mtl)}},
    {"sky",     {vs_sky_mtl, sizeof(vs_sky_mtl)},
                {fs_sky_mtl, sizeof(fs_sky_mtl)}},
    {"water",   {vs_water_mtl, sizeof(vs_water_mtl)},
                {fs_water_mtl, sizeof(fs_water_mtl)}},
    // "prop" shares the terrain vertex stage (world pos + normal + color
    // pass-through); only the fragment differs (vertex-color albedo).
    {"prop",    {vs_terrain_mtl, sizeof(vs_terrain_mtl)},
                {fs_prop_mtl, sizeof(fs_prop_mtl)}},
    // "path" (§8.1) also shares the terrain vertex stage: the path ribbon is a
    // world-space mesh with the same attributes, and only the cross-section
    // reading of them differs. Opaque with discard, like "foliage" — the
    // feather is an ordered dither, so it needs no blend and no sorting.
    {"path",    {vs_terrain_mtl, sizeof(vs_terrain_mtl)},
                {fs_path_mtl, sizeof(fs_path_mtl)}},
    // "overlay" is "unlit" with an alpha blend: the screen-space layer the HUD
    // (interaction prompts, later the crosshair) composites over the world.
    // Same shaders on purpose — the difference is render state, which is what
    // the logical-name -> state convention is for.
    {"overlay", {vs_unlit_mtl, sizeof(vs_unlit_mtl)},
                {fs_unlit_mtl, sizeof(fs_unlit_mtl)}},
    // Backend-internal depth-only pass for the sun shadow map.
    {"shadow",  {vs_shadow_mtl, sizeof(vs_shadow_mtl)},
                {fs_shadow_mtl, sizeof(fs_shadow_mtl)}},
    // Backend-internal caster pass for the carried lights' cube faces (writes
    // linear distance, not depth — see dfn_pointshadow.sh).
    {"point_shadow", {vs_point_shadow_mtl, sizeof(vs_point_shadow_mtl)},
                {fs_point_shadow_mtl, sizeof(fs_point_shadow_mtl)}},
};
#else
// Non-Apple platforms compile clean but ship no embedded shaders this stage
// (macOS focus per the stage-2 brief); load_program returns invalid handles.
const ProgramSource PROGRAM_TABLE[] = {
    {"terrain", {}, {}}, {"unlit", {}, {}}, {"debug", {}, {}},
    {"foliage", {}, {}}, {"shadow_cutout", {}, {}},
    {"upscale", {}, {}}, {"sky", {}, {}}, {"water", {}, {}}, {"prop", {}, {}},
    {"overlay", {}, {}}, {"shadow", {}, {}}, {"point_shadow", {}, {}},
    {"path", {}, {}},
};
#endif

struct UpscaleVertex {
    float x, y, z;
    float u, v;
};

// Fullscreen quad in clip space; v flipped so the internal target reads
// upright on Metal/D3D-style render-to-texture orientation.
const UpscaleVertex UPSCALE_QUAD_VERTICES[] = {
    {-1.0f, -1.0f, 0.0f, 0.0f, 1.0f},
    { 1.0f, -1.0f, 0.0f, 1.0f, 1.0f},
    {-1.0f,  1.0f, 0.0f, 0.0f, 0.0f},
    { 1.0f,  1.0f, 0.0f, 1.0f, 0.0f},
};
const uint16_t UPSCALE_QUAD_INDICES[] = {0, 1, 2, 1, 3, 2};

} // namespace

bgfx::ProgramHandle BgfxRenderer::Impl::make_program(const char* name) const {
    for (const ProgramSource& src : PROGRAM_TABLE) {
        if (std::strcmp(src.name, name) == 0 && src.vs.data != nullptr) {
            const bgfx::ShaderHandle vs =
                bgfx::createShader(bgfx::makeRef(src.vs.data, src.vs.size));
            const bgfx::ShaderHandle fs =
                bgfx::createShader(bgfx::makeRef(src.fs.data, src.fs.size));
            return bgfx::createProgram(vs, fs, true /* destroy shaders */);
        }
    }
    std::fprintf(stderr, "[render] unknown shader program: %s\n", name);
    return BGFX_INVALID_HANDLE;
}

BgfxRenderer::BgfxRenderer() : impl_(std::make_unique<Impl>()) {}

BgfxRenderer::~BgfxRenderer() {
    shutdown();
}

bool BgfxRenderer::init(const RendererInitParams& params) {
    Impl& im = *impl_;
    if (im.initialized) {
        return false;
    }
    if (params.native_window_handle == nullptr) {
        std::fprintf(stderr,
                     "[render] bgfx backend needs a native window handle "
                     "(use the null renderer for headless runs)\n");
        return false;
    }

    im.fb_width = params.framebuffer_width;
    im.fb_height = params.framebuffer_height;
    im.internal_width = params.internal_width > 0 ? params.internal_width
                                                  : params.framebuffer_width;
    im.internal_height = params.internal_height > 0 ? params.internal_height
                                                    : params.framebuffer_height;
    im.reset_flags = params.vsync ? BGFX_RESET_VSYNC : BGFX_RESET_NONE;

    bgfx::renderFrame(); // single-threaded mode: render on this thread

    bgfx::Init init;
#if defined(__APPLE__)
    init.type = bgfx::RendererType::Metal;
#else
    init.type = bgfx::RendererType::Count; // auto-pick (untested this stage)
#endif
    init.platformData.nwh = params.native_window_handle;
    init.resolution.width = im.fb_width;
    init.resolution.height = im.fb_height;
    init.resolution.reset = im.reset_flags;
    init.callback = &im.callback;
    if (!bgfx::init(init)) {
        std::fprintf(stderr, "[render] bgfx::init failed\n");
        return false;
    }

    im.mesh_layout.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Normal, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();
    im.debug_layout.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();
    im.upscale_layout.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
        .end();

    // Internal low-res target: point-sampled color + write-only depth (Q9).
    //
    // COVERAGE ANTIALIASING ON THE INTERNAL BUFFER, AND IT IS THE FIX FOR THE
    // USER'S OLDEST COMPLAINT («при беге трясет», «всё дергает и
    // перерисовывается очень рябью»). The chain that lands here, none of it
    // derived in this file: it is not camera motion (head_bob=0 leaves the
    // frame pair bit-identical), not the shadow map, and not foliage detail —
    // flora measured every geometric lever they own and the canopy is already
    // at the bottom of that curve. What it IS: at RUN_SPEED a silhouette at
    // distance d translates 11.7/d pixels per frame, so past ~12 m NOTHING in
    // the picture can move a whole pixel — it can only FLIP. The stride sweep
    // is linear in the step (0.229/0.451/0.864/1.691/3.167 % at
    // 0.0125/0.025/0.05/0.10/0.20 m), which is the signature of an edge
    // crossing a pixel CENTRE rather than of content aliasing, and internal
    // resolution does not move it (320x180 0.927 %, 1280x720 0.887 % against
    // 640x360's 0.864 %). A geometric edge crossing a pixel centre was
    // all-or-nothing; MSAA makes a fraction of a pixel of motion produce a
    // fraction of the colour change.
    //
    // THIS DOES NOT UN-PIXELATE THE GAME, which is the objection to answer
    // before the objection is raised. The pixel GRID is unchanged — 640x360
    // internal, integer-upscaled, point-sampled. MSAA only decides what
    // colour each of those same pixels gets; it adds shades, not resolution.
    //
    // Sample count via DFN_MSAA (0/1 = off, 2, 4, 8), default MSAA 4x —
    // measured with DFN_FLORA_PROBE + DFN_WIND_FREEZE, one 0.05 m stride at
    // RUN_SPEED, share of screen flipping by more than 64 luma, control
    // 0.000 % (near canopy / treeline): see the UPD entry for the table.
    // The SETTING is the source; DFN_MSAA still overrides it for tooling, the
    // same precedence settings.cfg has everywhere else (lead's one-line carve
    // into this file -- the field it reads is RendererInitParams::msaa_samples,
    // added at the same time, and leaving the setting inert would have been a
    // silent no-op of exactly the class this file spent the day fixing).
    uint64_t msaa_flags = BGFX_TEXTURE_RT_MSAA_X4;
    im.internal_samples = 4;
    {
        const uint32_t req = params.msaa_samples;
        switch (req) {
            case 0:
            case 1: msaa_flags = BGFX_TEXTURE_RT; im.internal_samples = 1; break;
            case 2: msaa_flags = BGFX_TEXTURE_RT_MSAA_X2; im.internal_samples = 2; break;
            case 8: msaa_flags = BGFX_TEXTURE_RT_MSAA_X8; im.internal_samples = 8; break;
            default: break;
        }
    }
    if (const char* m = std::getenv("DFN_MSAA")) {
        switch (std::atoi(m)) {
            case 0:
            case 1: msaa_flags = BGFX_TEXTURE_RT; im.internal_samples = 1; break;
            case 2: msaa_flags = BGFX_TEXTURE_RT_MSAA_X2; im.internal_samples = 2; break;
            case 8: msaa_flags = BGFX_TEXTURE_RT_MSAA_X8; im.internal_samples = 8; break;
            case 4: msaa_flags = BGFX_TEXTURE_RT_MSAA_X4; im.internal_samples = 4; break;
            default: break;
        }
    }
    const uint64_t color_flags = msaa_flags | BGFX_SAMPLER_MIN_POINT
                               | BGFX_SAMPLER_MAG_POINT | BGFX_SAMPLER_MIP_POINT
                               | BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP;
    const bgfx::TextureHandle color = bgfx::createTexture2D(
        static_cast<uint16_t>(im.internal_width),
        static_cast<uint16_t>(im.internal_height), false, 1,
        bgfx::TextureFormat::RGBA8, color_flags);
    // The depth attachment MUST carry the same sample count or the pass will
    // not build; WRITE_ONLY keeps it from allocating a resolve target. Note
    // BGFX_TEXTURE_RT_MSAA_* is a 3-bit FIELD, not a set of additive bits
    // (RT itself is the field's value 1), so the flags are ORed in whole.
    const bgfx::TextureHandle depth = bgfx::createTexture2D(
        static_cast<uint16_t>(im.internal_width),
        static_cast<uint16_t>(im.internal_height), false, 1,
        bgfx::TextureFormat::D32F, msaa_flags | BGFX_TEXTURE_RT_WRITE_ONLY);
    const bgfx::TextureHandle attachments[] = {color, depth};
    im.internal_fb = bgfx::createFrameBuffer(2, attachments, true);

    im.s_tex_color = bgfx::createUniform("s_texColor", bgfx::UniformType::Sampler);
    im.u_params = bgfx::createUniform("u_params", bgfx::UniformType::Vec4);
    im.u_env_params =
        bgfx::createUniform("u_envParams", bgfx::UniformType::Vec4, ENV_PARAM_VEC4S);
    im.u_post_params = bgfx::createUniform("u_postParams", bgfx::UniformType::Vec4);
    im.u_palette =
        bgfx::createUniform("u_palette", bgfx::UniformType::Vec4, PALETTE_SIZE);
    im.quad_vb = bgfx::createVertexBuffer(
        bgfx::makeRef(UPSCALE_QUAD_VERTICES, sizeof(UPSCALE_QUAD_VERTICES)),
        im.upscale_layout);
    im.quad_ib = bgfx::createIndexBuffer(
        bgfx::makeRef(UPSCALE_QUAD_INDICES, sizeof(UPSCALE_QUAD_INDICES)));
    im.upscale_program = im.make_program("upscale");
    im.debug_program = im.make_program("debug");
    im.sky_program = im.make_program("sky");

    // Sun shadow map (в1): depth-only target with a hardware compare sampler
    // (one hard tap — the pixelated edge fits the art style). D16 preferred,
    // D32F fallback; if neither works, shadows stay off (shadow_active false)
    // and rendering is stage-3b lighting — never a crash (Rule 3 spirit).
    {
        constexpr uint64_t depth_flags = BGFX_TEXTURE_RT
                                       | BGFX_SAMPLER_COMPARE_LEQUAL
                                       | BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP;
        bgfx::TextureFormat::Enum depth_fmt = bgfx::TextureFormat::D16;
        if (!bgfx::isTextureValid(0, false, 1, depth_fmt, depth_flags)) {
            depth_fmt = bgfx::TextureFormat::D32F;
        }
        if (bgfx::isTextureValid(0, false, 1, depth_fmt, depth_flags)) {
            im.shadow_map = bgfx::createTexture2D(SHADOW_MAP_SIZE, SHADOW_MAP_SIZE,
                                                  false, 1, depth_fmt, depth_flags);
            im.shadow_fb = bgfx::createFrameBuffer(1, &im.shadow_map, false);
        } else {
            std::fprintf(stderr, "[render] no depth format for the shadow map; "
                                 "sun shadows disabled\n");
        }
        im.shadow_program = im.make_program("shadow");
        im.shadow_cutout_program = im.make_program("shadow_cutout");
        im.s_shadow_map =
            bgfx::createUniform("s_shadowMap", bgfx::UniformType::Sampler);
        im.u_light_mtx = bgfx::createUniform("u_lightMtx", bgfx::UniformType::Mat4);
        im.u_shadow_params =
            bgfx::createUniform("u_shadowParams", bgfx::UniformType::Vec4);
    }

    // Carried-light cube shadows: one colour atlas (linear distance / radius)
    // plus its depth attachment, and the caster program. R32F preferred; RGBA8
    // is a legitimate fallback rather than a failure mode — 8 bits over a 9 m
    // torch is 3.5 cm of comparison resolution, which is finer than the
    // geometry we cast from. If neither exists the lights simply stop
    // shadowing (shadow_light_count stays 0) and still light — never a crash.
    {
        constexpr uint64_t atlas_flags = BGFX_TEXTURE_RT | BGFX_SAMPLER_MIN_POINT
                                       | BGFX_SAMPLER_MAG_POINT
                                       | BGFX_SAMPLER_MIP_POINT
                                       | BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP;
        bgfx::TextureFormat::Enum fmt = bgfx::TextureFormat::R32F;
        if (!bgfx::isTextureValid(0, false, 1, fmt, atlas_flags)) {
            fmt = bgfx::TextureFormat::RGBA8;
        }
        if (bgfx::isTextureValid(0, false, 1, fmt, atlas_flags)) {
            im.point_shadow_atlas = bgfx::createTexture2D(
                POINT_SHADOW_ATLAS_W, POINT_SHADOW_ATLAS_H, false, 1, fmt,
                atlas_flags);
            im.point_shadow_depth = bgfx::createTexture2D(
                POINT_SHADOW_ATLAS_W, POINT_SHADOW_ATLAS_H, false, 1,
                bgfx::TextureFormat::D16, BGFX_TEXTURE_RT_WRITE_ONLY);
            const bgfx::TextureHandle att[] = {im.point_shadow_atlas,
                                               im.point_shadow_depth};
            im.point_shadow_fb = bgfx::createFrameBuffer(2, att, false);
        } else {
            std::fprintf(stderr, "[render] no colour format for the point-light "
                                 "shadow atlas; carried lights will not cast\n");
        }
        im.point_shadow_program = im.make_program("point_shadow");
        im.s_point_shadow =
            bgfx::createUniform("s_pointShadow", bgfx::UniformType::Sampler);
        im.u_point_shadow_rows = bgfx::createUniform(
            "u_pointShadowRows", bgfx::UniformType::Vec4,
            MAX_SHADOW_POINT_LIGHTS * POINT_SHADOW_FACES * 4);
        im.u_point_shadow_params =
            bgfx::createUniform("u_pointShadowParams", bgfx::UniformType::Vec4);
        im.u_point_caster =
            bgfx::createUniform("u_pointCaster", bgfx::UniformType::Vec4);
    }

    // Sequential scene view (stage 3): sky first (backend), then the caller's
    // opaque submits, then transparents (RenderSystem orders them), then debug
    // lines in end_frame. Depth testing still resolves opaque occlusion.
    bgfx::setViewMode(VIEW_SCENE, bgfx::ViewMode::Sequential);

    im.palette_post = params.palette_post;
    im.palette = build_dfn_palette();

    im.initialized = true;
    return true;
}

void BgfxRenderer::shutdown() {
    Impl& im = *impl_;
    if (!im.initialized) {
        return;
    }
    if (!im.meshes.empty() || std::getenv("DFN_MESH_STATS") != nullptr) {
        // A count that does not return to zero is a leak; a peak near the limit
        // is the next crash. Both are invisible without this line.
        std::fprintf(stderr,
                     "[render] mesh handles at shutdown: %zu still live, peak %u "
                     "of %d, %llu created / %llu destroyed.\n",
                     im.meshes.size(), im.peak_meshes, BGFX_MESH_HANDLE_BUDGET,
                     static_cast<unsigned long long>(im.meshes_created),
                     static_cast<unsigned long long>(im.meshes_destroyed));
    }
    for (auto& [id, mesh] : im.meshes) {
        if (bgfx::isValid(mesh.vb)) {
            bgfx::destroy(mesh.vb);
        }
        if (bgfx::isValid(mesh.ib)) {
            bgfx::destroy(mesh.ib);
        }
    }
    im.meshes.clear();
    for (auto& [id, tex] : im.textures) {
        bgfx::destroy(tex);
    }
    im.textures.clear();
    for (auto& [id, prog] : im.programs) {
        bgfx::destroy(prog);
    }
    im.programs.clear();
    if (bgfx::isValid(im.upscale_program)) bgfx::destroy(im.upscale_program);
    if (bgfx::isValid(im.debug_program)) bgfx::destroy(im.debug_program);
    if (bgfx::isValid(im.sky_program)) bgfx::destroy(im.sky_program);
    if (bgfx::isValid(im.shadow_program)) bgfx::destroy(im.shadow_program);
    if (bgfx::isValid(im.shadow_cutout_program)) bgfx::destroy(im.shadow_cutout_program);
    if (bgfx::isValid(im.shadow_fb)) bgfx::destroy(im.shadow_fb);
    if (bgfx::isValid(im.shadow_map)) bgfx::destroy(im.shadow_map);
    if (bgfx::isValid(im.point_shadow_program)) bgfx::destroy(im.point_shadow_program);
    if (bgfx::isValid(im.point_shadow_fb)) bgfx::destroy(im.point_shadow_fb);
    if (bgfx::isValid(im.point_shadow_atlas)) bgfx::destroy(im.point_shadow_atlas);
    if (bgfx::isValid(im.point_shadow_depth)) bgfx::destroy(im.point_shadow_depth);
    if (bgfx::isValid(im.s_point_shadow)) bgfx::destroy(im.s_point_shadow);
    if (bgfx::isValid(im.u_point_shadow_rows)) bgfx::destroy(im.u_point_shadow_rows);
    if (bgfx::isValid(im.u_point_shadow_params)) bgfx::destroy(im.u_point_shadow_params);
    if (bgfx::isValid(im.u_point_caster)) bgfx::destroy(im.u_point_caster);
    if (bgfx::isValid(im.s_shadow_map)) bgfx::destroy(im.s_shadow_map);
    if (bgfx::isValid(im.u_light_mtx)) bgfx::destroy(im.u_light_mtx);
    if (bgfx::isValid(im.u_shadow_params)) bgfx::destroy(im.u_shadow_params);
    if (bgfx::isValid(im.quad_ib)) bgfx::destroy(im.quad_ib);
    if (bgfx::isValid(im.quad_vb)) bgfx::destroy(im.quad_vb);
    if (bgfx::isValid(im.u_params)) bgfx::destroy(im.u_params);
    if (bgfx::isValid(im.u_env_params)) bgfx::destroy(im.u_env_params);
    if (bgfx::isValid(im.u_post_params)) bgfx::destroy(im.u_post_params);
    if (bgfx::isValid(im.u_palette)) bgfx::destroy(im.u_palette);
    if (bgfx::isValid(im.s_tex_color)) bgfx::destroy(im.s_tex_color);
    if (bgfx::isValid(im.internal_fb)) bgfx::destroy(im.internal_fb);
    bgfx::frame(); // flush destroys (and any pending screenshot write)
    bgfx::shutdown();
    im.initialized = false;
}

void BgfxRenderer::resize(uint32_t framebuffer_width, uint32_t framebuffer_height) {
    Impl& im = *impl_;
    if (!im.initialized || framebuffer_width == 0 || framebuffer_height == 0) {
        return;
    }
    im.fb_width = framebuffer_width;
    im.fb_height = framebuffer_height;
    bgfx::reset(framebuffer_width, framebuffer_height, im.reset_flags);
    // The internal target is resolution-independent (Q9): only the upscale
    // rect changes, and it is recomputed every end_frame.
}

std::unique_ptr<IRenderer> create_bgfx_renderer() {
    return std::make_unique<BgfxRenderer>();
}

} // namespace dfn::platform
