#!/usr/bin/env python3
#
# File: tools/gen_constants.py
#
# Responsibility:
# - Generate <build>/dfn_generated/Constants.h from docs/NUMBERS.md so code and
#   the design document cannot diverge (Q54, Rule 14). Runs at CMake configure.
#
# Parsing contract (documented, deterministic):
# - Only markdown table rows whose first cell is `UPPER_SNAKE` in backticks.
# - Value cell, first token: int -> int64_t; float -> double; "a/b" -> double;
#   "1.309 (~75deg)" -> leading number; "AxB" (x or U+00D7) -> NAME_W / NAME_H
#   (+ NAME itself when A == B). Unparseable rows are skipped and listed in the
#   generated header's comment so the gap is visible, never silent.
# - Output: namespace dfn::config, inline constexpr, names verbatim from NUMBERS.
#
# Dependencies:
# - Uses: Python stdlib only.
# - Used by: CMake configure step (root CMakeLists), engine/core/config wrapper.
#
# AI Agents Notice:
# - Follow docs/ARCHITECTURE.md strictly.
# - Never hand-edit the generated header; change docs/NUMBERS.md instead.

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

NAME_RE = re.compile(r"^`(?P<name>[A-Z][A-Z0-9_]*)`$")
DIM_RE = re.compile(r"^(?P<a>\d+(?:\.\d+)?)[x×](?P<b>\d+(?:\.\d+)?)$")
FRAC_RE = re.compile(r"^(?P<n>\d+(?:\.\d+)?)/(?P<d>\d+(?:\.\d+)?)$")
NUM_RE = re.compile(r"^(?P<v>-?\d+(?:\.\d+)?)$")

def fmt(value: float) -> tuple[str, str]:
    """Return (c++ type, literal) — int64_t for whole values, double otherwise."""
    if float(value) == int(float(value)) and "." not in str(value):
        return "std::int64_t", str(int(float(value)))
    return "double", repr(float(value))

def parse_rows(md: str):
    consts: list[tuple[str, str, str]] = []  # (name, type, literal)
    skipped: list[str] = []
    for line in md.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        m = NAME_RE.match(cells[0])
        if not m:
            continue
        name = m.group("name")
        raw = cells[1]
        token = raw.split()[0] if raw.split() else ""

        if dm := DIM_RE.match(token):
            a, b = dm.group("a"), dm.group("b")
            ta, la = fmt(a)
            tb, lb = fmt(b)
            consts.append((f"{name}_W", ta, la))
            consts.append((f"{name}_H", tb, lb))
            if a == b:
                consts.append((name, ta, la))
        elif fm_ := FRAC_RE.match(token):
            v = float(fm_.group("n")) / float(fm_.group("d"))
            consts.append((name, "double", repr(v)))
        elif nm := NUM_RE.match(token):
            t, l = fmt(nm.group("v"))
            consts.append((name, t, l))
        else:
            skipped.append(f"{name} (value: {raw!r})")
    return consts, skipped

def main() -> int:
    ap = argparse.ArgumentParser(description="NUMBERS.md -> Constants.h generator")
    ap.add_argument("--numbers", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    md = Path(args.numbers).read_text(encoding="utf-8")
    consts, skipped = parse_rows(md)
    if not consts:
        print("gen_constants: no constants parsed — refusing to emit", file=sys.stderr)
        return 1

    seen: set[str] = set()
    lines = [
        "// GENERATED by tools/gen_constants.py from docs/NUMBERS.md — do not edit.",
        "// Change docs/NUMBERS.md and re-run CMake configure instead.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace dfn::config {",
        "",
    ]
    for name, ctype, literal in consts:
        if name in seen:
            print(f"gen_constants: duplicate constant {name}", file=sys.stderr)
            return 1
        seen.add(name)
        lines.append(f"inline constexpr {ctype} {name} = {literal};")
    lines.append("")
    if skipped:
        lines.append("// Skipped (non-numeric in NUMBERS.md — intentional, see the doc):")
        lines.extend(f"//   {s}" for s in skipped)
    lines.append("} // namespace dfn::config")
    lines.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
    print(f"gen_constants: {len(seen)} constants -> {out}"
          + (f" ({len(skipped)} skipped)" if skipped else ""))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
