#
# Created: 10:08:2026 - 19:56:11
# Last updated: 10:08:2026 - 19:56:11
# File: tools/stamp_build_commit.cmake
#
# Responsibility:
# - Writes dfn_buildinfo/BuildInfo.h with the commit the binary is being built
#   from. Run at BUILD time, not configure time.
#
# Dependencies:
# - Uses: git (optional; "unknown" without it).
# - Used by: engine/app/CMakeLists.txt via a custom target.
#
# Notes:
# - WHY BUILD TIME. Stamped at configure time, the string names whatever the
#   tree was when cmake last ran, which can be many commits behind the binary.
#   The field exists so that someone can later ask "was this capture taken
#   before or after the fix?" -- and a field that answers that question WRONGLY
#   is worse than no field, because it turns "I do not know which build this
#   is" into a confident false premise (Rule 34). Found by sim, whose capture
#   named a build two commits stale.
# - WHY "+dirty". A commit hash alone cannot describe a working tree with
#   uncommitted edits, which is the normal state while a bug is being chased --
#   exactly when captures get taken. Without the marker, two captures from two
#   different sets of local edits carry the identical string.
# - copy_if_different so an unchanged commit does not force a rebuild every
#   time, while a changed one does.
#
# AI Agents Notice:
# - Follow docs/ARCHITECTURE.md strictly. LEAD-owned (Rule 25).
#
# UPD:
# - 10:08:2026 - 19:56:11: Created (sim's finding: configure-time stamp named a stale build).

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE DFN_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
if(NOT DFN_COMMIT)
    set(DFN_COMMIT "unknown")
endif()

execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE DFN_DIRTY
    ERROR_QUIET)
if(DFN_DIRTY)
    set(DFN_COMMIT "${DFN_COMMIT}+dirty")
endif()

file(WRITE "${OUT}.tmp"
     "// Generated by tools/stamp_build_commit.cmake at build time. Do not edit.\n"
     "#pragma once\n"
     "#define DFN_BUILD_COMMIT \"${DFN_COMMIT}\"\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
